### ISSUE TITLE
gRPC requests are failed for restarted modules

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcc-piccolo#2] opened 2021-06-24 06:33 UTC
If there are some restarted modules.
gRPC requests for that modules will fail.

I think we should re-create gRPC connection for each modules when the module is restarted.

@hcloudclassic

**Comment by hcloudclassic** [comment] 2021-06-24 06:36
I saw that issues too.
The issue is fixed in https://github.com/hcloud-classic/hcc-piccolo/commit/a7a91f11a2064e639663694fc8d3642f911caadb

**Closed as completed** 2021-06-24 06:37 UTC
Labels: bug, enhancement
